### ISSUE TITLE
Importance scores

### ISSUE THREAD

**Issue by gergopool** [apostolikas/Language-Specific-Subnetworks#7]
Modify the current mask.py, so it also returns with the importance scores of the final masked version of the network. Save these importance scores similarly as we saved the masks, but not to *results/pruned_masks* folder, choose something else pls. E.g. *results/importance_scores*. The filenames should be the same though (e.g. en_0.pkl)

Development tip: To save time, don't wait until the script prunes things. Write your method after the first importance scores is calculated, return with that importance-matrix, save, check if files are saved and desired and they contain information you wanted. Also, choose a small sampling value for masking, e.g. 100 examples. With these tricks, you can actually develop everything on CPU, you won't need GPU. If it runs smoothly, then it's ready to be moved to the end of pruning, so it saves the importance scores of the last/final masked network.

**Comment by vasilisvyth** [comment]
I started working on it yesterday. I will just create a new branch because I made some changes. I think of returning the importance scores at each timestep to see if we can get any additional insight from it.
